repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0   # ✅ Compatible with Python 3.8.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4    # ✅ Compatible with Python 3.8.0
    hooks:
      - id: flake8
